/**
 * All portfolio media. Files live in /public/media and are referenced from the site root.
 *
 * Fields:
 *   src     required  MP4 (H.264) path
 *   webm    optional  WebM path, offered to the browser before the MP4
 *   width   required  intrinsic pixel width
 *   height  required  intrinsic pixel height
 *   label   optional  short text shown on hover
 *   poster  optional  still image shown before the clip loads
 *   alt     optional  accessible description of the clip
 */
export const media = [
  {
    src: '/media/cat-01.mp4',
    webm: '/media/cat-01.webm',
    width: 1280,
    height: 720,
    label: 'Ambush',
    poster: '/media/cat-01.jpg',
  },
  {
    src: '/media/cat-02.mp4',
    width: 720,
    height: 1280,
    label: 'Play',
    poster: '/media/cat-02.jpg',
  },
  {
    src: '/media/cat-03.mp4',
    width: 1280,
    height: 720,
    label: 'Lizard',
    poster: '/media/cat-03.jpg',
  },
  {
    src: '/media/cat-04.mp4',
    width: 576,
    height: 720,
    label: 'Water',
    poster: '/media/cat-04.jpg',
  },
  {
    src: '/media/cat-05.mp4',
    width: 1280,
    height: 720,
    label: 'Grooming',
    poster: '/media/cat-05.jpg',
  },
  {
    src: '/media/cat-06.mp4',
    width: 720,
    height: 1280,
    label: 'Yawn',
    poster: '/media/cat-06.jpg',
  },
  {
    src: '/media/cat-07.mp4',
    webm: '/media/cat-07.webm',
    width: 720,
    height: 720,
    label: 'Kneading',
    poster: '/media/cat-07.jpg',
  },
  {
    src: '/media/cat-08.mp4',
    width: 1280,
    height: 720,
    poster: '/media/cat-08.jpg',
  },
  {
    src: '/media/cat-32.mp4',
    width: 720,
    height: 1280,
    label: 'Door',
    poster: '/media/cat-32.jpg',
  },
  {
    src: '/media/cat-18.mp4',
    width: 1280,
    height: 720,
    label: 'Wash',
    poster: '/media/cat-18.jpg',
  },
  {
    src: '/media/cat-10.mp4',
    width: 720,
    height: 1280,
    label: 'Gaze',
    poster: '/media/cat-10.jpg',
  },
  {
    src: '/media/cat-24.mp4',
    width: 576,
    height: 720,
    label: 'Thirst',
    poster: '/media/cat-24.jpg',
  },
  {
    src: '/media/cat-28.mp4',
    width: 720,
    height: 720,
    label: 'Purr',
    poster: '/media/cat-28.jpg',
  },
  {
    src: '/media/cat-19.mp4',
    width: 1280,
    height: 720,
    label: 'Laser',
    poster: '/media/cat-19.jpg',
  },
  {
    src: '/media/cat-12.mp4',
    width: 720,
    height: 1280,
    label: 'Tabby',
    poster: '/media/cat-12.jpg',
  },
  {
    src: '/media/cat-25.mp4',
    width: 576,
    height: 720,
    label: 'Madrid',
    poster: '/media/cat-25.jpg',
  },
  {
    src: '/media/cat-31.mp4',
    width: 1280,
    height: 720,
    label: 'Prowl',
    poster: '/media/cat-31.jpg',
  },
  {
    src: '/media/cat-13.mp4',
    width: 720,
    height: 1280,
    label: 'Kittens',
    poster: '/media/cat-13.jpg',
  },
  {
    src: '/media/cat-33.mp4',
    width: 720,
    height: 720,
    label: 'Sunbath',
    poster: '/media/cat-33.jpg',
  },
  {
    src: '/media/cat-20.mp4',
    width: 1280,
    height: 720,
    label: 'Litter',
    poster: '/media/cat-20.jpg',
  },
  {
    src: '/media/cat-34.mp4',
    width: 576,
    height: 720,
    label: 'Blink',
    poster: '/media/cat-34.jpg',
  },
  {
    src: '/media/cat-29.mp4',
    width: 720,
    height: 720,
    label: 'Leap',
    poster: '/media/cat-29.jpg',
  },
  {
    src: '/media/cat-14.mp4',
    width: 720,
    height: 1280,
    label: 'Siamese',
    poster: '/media/cat-14.jpg',
  },
  {
    src: '/media/cat-40.mp4',
    width: 1280,
    height: 720,
    label: 'Catnip',
    poster: '/media/cat-40.jpg',
  },
  {
    src: '/media/cat-26.mp4',
    width: 576,
    height: 720,
    label: 'Stretch',
    poster: '/media/cat-26.jpg',
  },
  {
    src: '/media/cat-35.mp4',
    width: 720,
    height: 1280,
    label: 'Cito',
    poster: '/media/cat-35.jpg',
  },
  {
    src: '/media/cat-21.mp4',
    width: 1280,
    height: 720,
    label: 'Jellybelly',
    poster: '/media/cat-21.jpg',
  },
  {
    src: '/media/cat-39.mp4',
    width: 720,
    height: 720,
    label: 'Hiss',
    poster: '/media/cat-39.jpg',
  },
  {
    src: '/media/cat-15.mp4',
    width: 720,
    height: 1280,
    label: 'Lick',
    poster: '/media/cat-15.jpg',
  },
  {
    src: '/media/cat-36.mp4',
    width: 576,
    height: 720,
    label: 'Stairs',
    poster: '/media/cat-36.jpg',
  },
  {
    src: '/media/cat-30.mp4',
    width: 720,
    height: 720,
    label: 'Pounce',
    poster: '/media/cat-30.jpg',
  },
  {
    src: '/media/cat-43.mp4',
    width: 1280,
    height: 720,
    label: 'Sunset',
    poster: '/media/cat-43.jpg',
  },
  {
    src: '/media/cat-16.mp4',
    width: 720,
    height: 1280,
    label: 'Tokyo',
    poster: '/media/cat-16.jpg',
  },
  {
    src: '/media/cat-42.mp4',
    width: 576,
    height: 720,
    label: 'Aquarium',
    poster: '/media/cat-42.jpg',
  },
  {
    src: '/media/cat-23.mp4',
    width: 1280,
    height: 720,
    poster: '/media/cat-23.jpg',
  },
  {
    src: '/media/cat-37.mp4',
    width: 720,
    height: 1280,
    label: 'Desk',
    poster: '/media/cat-37.jpg',
  },
  {
    src: '/media/cat-41.mp4',
    width: 720,
    height: 720,
    label: 'Snooze',
    poster: '/media/cat-41.jpg',
  },
  {
    src: '/media/cat-38.mp4',
    width: 576,
    height: 720,
    label: 'Curtain',
    poster: '/media/cat-38.jpg',
  },
  {
    src: '/media/cat-17.mp4',
    width: 720,
    height: 1280,
    label: 'Scratch',
    poster: '/media/cat-17.jpg',
  },
  {
    src: '/media/cat-44.mp4',
    width: 720,
    height: 720,
    label: 'Lounge',
    poster: '/media/cat-44.jpg',
  },
];
